### ISSUE TITLE
Error - Object 'S1' not found

### ISSUE THREAD

**Issue by vkorobeynyk** [ZhangLabGT/scMultiSim#1]
Hi,

I am trying to go through the .Rmd vignettes and while running: 

`results <- SimulateTrueCounts(GRN_params, num_cells = 1000, unregulated_to_regulated_gene_ratio = 0.1, num_evfs = 500, diffEVF_fraction = 0.9, Sigma = 0.1,
                              atac_effect = 0.5, beta = 0.4, d = 1, num_cycles = 2, cycle_length = 1.0, intrinsic_noise = 1, phyla = p3, randseed = 0,
                              do_velocity = T, nregions_distribution = cumsum(c(0.1, 0.5, 0.4)))`

I get an error:

`Error in RNA_SEQ(evf_all, phyla, num_genes, num_cells, num_regulators,  : 
  object 'S1' not found`

Any idea for a solution?

**Comment by lhc70000** [comment]
Hi, sorry for the late reply! This repo contains a previous version of scMultiSim which links to an obsolete vignette, and I just fixed it. Please follow [vignettes/sim_new.Rmd](https://github.com/ZhangLabGT/scMultiSim/blob/main/vignettes/sim_new.Rmd) for the latest version. 

We are still in the process of adding more tutorials and documentation. Feel free to reach out if you have any other questions!
