### ISSUE TITLE
Simulate RNA expression data using predetermined, cell cluster-specific GRNs

### ISSUE THREAD

**Issue by AnneHartebrodt** [ZhangLabGT/scMultiSim#11]
Hello,

thank you for this amazing tool.  

I would like to simulate RNASeq expression data where each cluster has it's own underlying GRN. I don't need the trajectory, I would like to have $n$ distinct clusters. Intuitively this must be possible to have two separate GRNs, since there is already the ```dynamic.GRN``` option, but I am unsure how to tie the GRN to the cell clusters. 

My first option would be to generate two datasets and somehow merge them. However, I think this option is bad, because it does not use the capacity of the package at it's best.

Using the ```dynamic.GRN``` option with settings that modify the GRN strongly to obtain two reasonably dissimilar GRNs, would be a second option, and the base  CIF and GIF vectors would remain the same. (I hope, I understood correctly that they do not change regardless of the population). However, I think, in order to simulate a realistic effect, I think the diff-CIF vector needs to somehow be tied to the GRN, otherwise the GRN differentiating the cell types would be disconnected from the expression values.

Is there is a way of controlling the parameters so tightly to make this work? Or would you have another idea? 

I would appreciate your input,

Anne

**Comment by lhc70000** [comment]
Hi Anne, sorry for the late reply.

Yes, I think `dynamic.GRN` can only generate a dataset where each cell has its own GRN and is not suitable for this case.

The first thing I can think of is that:
- For example you want to generate 2 clusters;
- Then you can generate two datasets using the same random seed but different GRNs, and each dataset has two clusters.
- Take cluster 1 from the first dataset and cluster 2 from the second dataset.

However, you might want to verify that other factors (such as the non-diff-CIF) don't change between these two datasets. It would be ideal if this can be achieved using the same random seed, but I'm not sure since we removed some `set.seed` usages when submitting to BioConductor.

If this doesn't work, please let me know and I will be happy to add such an option in scMultiSim.

**Comment by AnneHartebrodt** [comment]
Hello! Thanks for the detailed reply! 

I was unsure, if the underlying matrices from which the sampling parameters are taken could be reasonably similar. 

I will try it and compare if the CIF vectors are the same for the generation of the expression data. If it looks too suspicious I will come back to you. I think I can reinsert the seed in the code if that is the issue.

I had some idea about how it could be adapted, but I currently don't have the time to implement it.

**Comment by AnneHartebrodt** [comment]
Hi again,

In case anyone else is interested, I think this worked reasonably well. 

# Procedure:
- Use an underlying GRN which is subset into two sub-GRNs by modifying the weights of the edges.
- Generate data for each GRN with otherwise same settings and with the same seed!! By setting the same seed the CIF and GIVs will be more or less identical (there are some small randomness effects which cannot be controlled, but they are minor). The GRN effect is added after, so that will simulated data drawn from the same underlying mechanisms.
- Combine the data

Depending on how the GRN is modified you can control whether the differentiation tree or the GRN are the main drivers of the GRN.

- Setting edge weights to 0 (a small pseudo-weight) will lead to data where the effect of the GRN is stronger than the effect of the differentiation tree (cluster). This means data generated from the same GRN will appear more similar to each other (at least on GRN level) than data that are in the same cluster in the differentiation tree
- Modifying the GRN less strongly will lead to data where the effect of the cluster is more pronounced than the effect of the differentiation tree.
- _Genes which are not regulated by the GRN should be removed (argument: unregulated.gene.ratio) Because they will be drawn independently for the two runs and hence will create a spurious clustering which should be avoided._

Cheers,
Anne

# Code
```{R, echo=F}
knitr::opts_chunk$set(fig.width=12, fig.height=12) 
require(scMultiSim)
require(data.table)
require(ggplot2)
require(ComplexHeatmap)
```

# Generate three clusters from each GRN

- Use a GRN that is subset into two distinct GRNs by reducing the effect to almost 0
- Use a differentiation tree with 3 leaves (Phyla3) and without velocity
- Generate a data from each network
- Combine data

## Create the GRNs
```{R}
data(GRN_params_100)
grn<-as.data.table(GRN_params_100)

## Define two subnetworks goverened by two different sets of transcription factors.
down1<-c(6, 10, 91)
down2<-c(80,19,2)

#fake_master<-data.table(regulated.gene = c(down1,down2), regulator.gene = c(101,101,101, 102,102,102), regulator.effect = c(5,5,5, 5,5,5))
#grn<-rbind(grn, fake_master)
grn1<-grn

#down1<-c(6, 10, 91, 101)
grn1[regulator.gene %in% down1, 'regulator.effect']<-0.01


grn2<-grn
#down2<-c(80,19,2, 102)
grn2[regulator.gene %in% c(down2,102), 'regulator.effect']<-0.01

```

## Simulate the data using the same seed
```{R}

set.seed(12)
results <- sim_true_counts(list(
  # required options
  GRN = grn1,
  tree = Phyla3(),
  num.cells = 750,
  # optional options
  num.cif = 50,
  discrete.cif = T,
  cif.sigma = 0.1,
  unregulated.gene.ratio  = 0.05))

# add_expr_noise(
#   results,
#   # options go here
#   alpha_mean = 1e4
# )

set.seed(12)
results2 <- sim_true_counts(list(
  # required options
  GRN = grn2,
  tree = Phyla3(),
  num.cells = 750,
  # optional options
  num.cif = 50,
  discrete.cif = T,
  cif.sigma = 0.1,
  unregulated.gene.ratio = 0.05))

# add_expr_noise(
#   results2,
#   # options go here
#   alpha_mean = 1e4
# )

```


```{R}
## Look at the data on a TNSE plot
counts<-cbind(results$counts, results2$counts)
#counts<-scale(counts)

pgrn<-plot_tsne(counts, labels = c(rep("Simulation 1", 750), rep('Simulation 2',750)))+
  theme_bw()+
  theme(legend.position = 'bottom')+
  ylab('tSNE2')+
  xlab('tSNE1')+
  scale_color_manual(values = c('lightblue', 'blue'))+
  ggtitle('Two simulations with identical seeds using a different GRN for each cluster')

pgrn
```

![unnamed-chunk-4-1](https://github.com/user-attachments/assets/b93133eb-559b-40e8-81ff-1f685be0797c)

## Plot the data as a heatmap as is
```{R}

ha = HeatmapAnnotation(
  simulation = anno_simple(c(rep("Simulation 1", 750), rep('Simulation 2',750))),
  cell = anno_simple(c(results$cell_meta$pop, results2$cell_meta$pop)),
  annotation_name_side = "left" )

ComplexHeatmap::Heatmap(counts, row_names_gp = gpar(fontsize = 5), 
                        top_annotation = ha)

```
![unnamed-chunk-5-1](https://github.com/user-attachments/assets/f0812852-bdd9-43ac-bc20-20494a0ec198)


## Remove the non-regulated genes from the data
Cells in same simulation are closer together than cells in the same leaf of the differentiation tree from different simulations. This hence does not simulate a situation where cell populations are disregulated.
```{R}
##
nocor<- !(sapply(rownames(counts), function(x) startsWith(x, 'gene')))
ComplexHeatmap::Heatmap(counts[nocor,], row_names_gp = gpar(fontsize = 5), 
                        top_annotation = ha)

```

![unnamed-chunk-6-1](https://github.com/user-attachments/assets/3892f475-6ced-4be2-84aa-21ce0be4c856)


# Less drastic change of the GRNSs
Modify the GRN less strongly by reducing selected edges by 0.5 instead of setting them to 0.01
- split grn into two chunks
- reduce first half of genes in first GRN by 0.5 and second half of genes by 0.5 in second GRN

## Create the GRNs
```{R}
data(GRN_params_100)
grn<-as.data.table(GRN_params_100)

## Define two subnetworks goverened by two different sets of transcription factors.
down1<-c(6, 10, 91)
down2<-c(80,19,2)

## add fake master transcription factors
#fake_master<-data.table(regulated.gene = c(down1,down2), regulator.gene = c(101,101,101, 102,102,102), regulator.effect = c(5,5,5, 5,5,5))
#grn<-rbind(grn, fake_master)
grn1<-grn

#down1<-c(6, 10, 91, 101)
grn1[regulator.gene %in% down1, 'regulator.effect']<-grn1[regulator.gene %in% down1, 'regulator.effect']-0.5


grn2<-grn
#down2<-c(80,19,2, 102)
grn2[regulator.gene %in% c(down2,102), 'regulator.effect']<-grn2[regulator.gene %in% c(down2,102), 'regulator.effect']-0.5

```
## Simulate the data using the same seed
```{R}

set.seed(12)
results <- sim_true_counts(list(
  # required options
  GRN = grn1,
  tree = Phyla3(),
  num.cells = 750,
  # optional options
  num.cif = 50,
  discrete.cif = T,
  cif.sigma = 0.1,
  unregulated.gene.ratio  = 0.05,
  diff.cif.fraction = 0.25))

# add_expr_noise(
#   results,
#   # options go here
#   alpha_mean = 1e4
# )

set.seed(12)
results2 <- sim_true_counts(list(
  # required options
  GRN = grn2,
  tree = Phyla3(),
  num.cells = 750,
  # optional options
  num.cif = 50,
  discrete.cif = T,
  cif.sigma = 0.1,
  unregulated.gene.ratio = 0.05,
  diff.cif.fraction = 0.25))

# add_expr_noise(
#   results2,
#   # options go here
#   alpha_mean = 1e4
# )

```

```{R}
## Look at the data on a TNSE plot
counts<-cbind(results$counts, results2$counts)
#counts<-scale(counts)

pgrn<-plot_tsne(counts, labels = c(rep("Simulation 1", 750), rep('Simulation 2',750)))+
  theme_bw()+
  theme(legend.position = 'bottom')+
  ylab('tSNE2')+
  xlab('tSNE1')+
  scale_color_manual(values = c('lightblue', 'blue'))+
  ggtitle('Two simulations with identical seeds using a different GRN for each cluster')

pgrn
```
![unnamed-chunk-9-1](https://github.com/user-attachments/assets/41f7eb9a-9998-41f4-b40d-4cff45e569c4)


## Remove the non-regulated genes from the data

```{R}
##
nocor<- !(sapply(rownames(counts), function(x) startsWith(x, 'gene')))
ComplexHeatmap::Heatmap(counts[nocor,], row_names_gp = gpar(fontsize = 5), 
                        top_annotation = ha)

```

![unnamed-chunk-11-1](https://github.com/user-attachments/assets/c02d726c-21bb-4742-b57f-2851004a47ec)
