### ISSUE TITLE
Option GRN is required but not presented.

### ISSUE THREAD

**Issue by ivanovaos** [ZhangLabGT/scMultiSim#2]
Hello, 

Thanks for the great tool! I am testing it out, and as far as I understand GRN input is optional? However, when I am trying to run with options 

```
options_ = list(
  rand.seed = 0,
  num.cells = 1000,
  num.cifs = 500,
  tree = Phyla5(),
  diff.cif.fraction = 0.8,
  do.velocity = T,
  intrinsic.noise = 1
  # debug = T
)
```

I get `"Error in OP(GRN) : Option GRN is required but not presented." `
Is this supposed to be this way? 

Thank you!

**Comment by lhc70000** [comment]
Hi, please set the GRN to `NA`:

```
options_ = list(
  rand.seed = 0,
  num.cells = 1000,
  num.cifs = 500,
  tree = Phyla5(),
  GRN = NA,
  diff.cif.fraction = 0.8,
  do.velocity = T,
  intrinsic.noise = 1
)
```

I also found another problem and just pushed the updated code, so please pull/clone the repo again before running it (sorry for that; we are still preparing the code for the release). Please let me know if you have other questions. Thanks!
